name:                todolist
version:             0.1.0.0
github:              "githubuser/todolist"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/todolist#readme>

dependencies:
- base >= 4.7 && < 5
- wai == 3.2.4

library:
  source-dirs: src
  dependencies:
    - base
    - servant
    - servant-server
    - warp
    - blaze-html
    - blaze-markup     
    - servant-blaze    
    - text             
    - mtl
    - http-media     
    - wai-cors     
    - wai-extra 
    - http-api-data
    - hspec-wai
    - time
    - aeson        # ← Add this line

executables:
  todolist-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - todolist
      - servant
      - servant-server
      - warp
      - blaze-html
      - blaze-markup   
      - servant-blaze  
      - text
      - mtl
      - http-media     
      - wai-cors     
      - wai-extra 
      - http-api-data
      - hspec-wai
      - time
      - aeson        # ← And add this too
